# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'have_book_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 260)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 751, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.main_box = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.main_box.setContentsMargins(0, 0, 0, 0)
        self.main_box.setObjectName("main_box")
        self.view = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.view.setObjectName("view")
        self.view.setColumnCount(0)
        self.view.setRowCount(0)
        self.main_box.addWidget(self.view)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_open = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.bt_open.setMinimumSize(QtCore.QSize(100, 25))
        self.bt_open.setMaximumSize(QtCore.QSize(100, 25))
        self.bt_open.setObjectName("bt_open")
        self.horizontalLayout_2.addWidget(self.bt_open)
        self.bt_append = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.bt_append.setMinimumSize(QtCore.QSize(120, 25))
        self.bt_append.setMaximumSize(QtCore.QSize(120, 25))
        self.bt_append.setObjectName("bt_append")
        self.horizontalLayout_2.addWidget(self.bt_append)
        self.bt_dell = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.bt_dell.setMinimumSize(QtCore.QSize(110, 25))
        self.bt_dell.setMaximumSize(QtCore.QSize(110, 25))
        self.bt_dell.setObjectName("bt_dell")
        self.horizontalLayout_2.addWidget(self.bt_dell)
        self.bt_new_inform = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.bt_new_inform.setMinimumSize(QtCore.QSize(110, 25))
        self.bt_new_inform.setMaximumSize(QtCore.QSize(110, 25))
        self.bt_new_inform.setObjectName("bt_new_inform")
        self.horizontalLayout_2.addWidget(self.bt_new_inform)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.main_box.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bt_found = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.bt_found.setMinimumSize(QtCore.QSize(60, 25))
        self.bt_found.setMaximumSize(QtCore.QSize(60, 25))
        self.bt_found.setObjectName("bt_found")
        self.horizontalLayout_3.addWidget(self.bt_found)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(80, 25))
        self.label.setMaximumSize(QtCore.QSize(80, 25))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.le_name = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.le_name.setMinimumSize(QtCore.QSize(140, 23))
        self.le_name.setMaximumSize(QtCore.QSize(16777215, 23))
        self.le_name.setObjectName("le_name")
        self.horizontalLayout_3.addWidget(self.le_name)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(90, 25))
        self.label_2.setMaximumSize(QtCore.QSize(90, 25))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.le_class = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.le_class.setMinimumSize(QtCore.QSize(0, 23))
        self.le_class.setMaximumSize(QtCore.QSize(130, 23))
        self.le_class.setObjectName("le_class")
        self.horizontalLayout_3.addWidget(self.le_class)
        self.main_box.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_open.setText(_translate("Form", "Открыть пункт"))
        self.bt_append.setText(_translate("Form", "Добавить должника"))
        self.bt_dell.setText(_translate("Form", "Удалить должника"))
        self.bt_new_inform.setText(_translate("Form", "Обновить таблицу"))
        self.bt_found.setText(_translate("Form", "Найти"))
        self.label.setText(_translate("Form", "Имя должника:"))
        self.label_2.setText(_translate("Form", "Класс должника:"))
