# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        #self.menu_param = QtWidgets.QMenu(self.menubar)
        #self.menu_param.setObjectName("menu_param")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.made_proj = QtWidgets.QAction(MainWindow)
        self.made_proj.setObjectName("made_proj")
        self.made_ibok = QtWidgets.QAction(MainWindow)
        self.made_ibok.setObjectName("made_ibok")
        self.import_file = QtWidgets.QAction(MainWindow)
        self.import_file.setObjectName("import_file")
        self.file_save = QtWidgets.QAction(MainWindow)
        self.file_save.setObjectName("file_save")
        self.menu_file.addAction(self.made_proj)
        self.menu_file.addAction(self.made_ibok)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.import_file)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.file_save)
        
        #self.file_sample = QtWidgets.QMenu(MainWindow)
        #self.file_sample.setObjectName("file_sample")
        #self.menu_file.addMenu(self.file_sample)
        #
        #self.file_sample_1 = QtWidgets.QAction(MainWindow)
        #self.file_sample_1.setObjectName("file_sample_1")
        #self.file_sample.addAction(self.file_sample_1)
        #
        #self.file_sample_2 = QtWidgets.QAction(MainWindow)
        #self.file_sample_2.setObjectName("file_sample_2")
        #self.file_sample.addAction(self.file_sample_2)
        
        self.menubar.addAction(self.menu_file.menuAction())
        #self.menubar.addAction(self.menu_param.menuAction())
        #self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_file.setTitle(_translate("MainWindow", "Файл"))
        #self.menu_param.setTitle(_translate("MainWindow", "Параметры"))# 
        #self.menu_help.setTitle(_translate("MainWindow", "Справка"))# 
        self.made_proj.setText(_translate("MainWindow", "Создать проект"))# W
        self.made_ibok.setText(_translate("MainWindow", "Создать описание книги"))# 
        self.import_file.setText(_translate("MainWindow", "Импортировать файл"))# 
        self.file_save.setText(_translate("MainWindow", "Сохранить файл"))# 
        # self.file_sample.setTitle(_translate("MainWindow", "Шаблоны"))#
        # self.file_sample_1.setText(_translate("MainWindow", "Шаблон: 'Классы и шлола'"))# 
        # self.file_sample_2.setText(_translate("MainWindow", "Шаблон: 'Методические пособия'"))# 