# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pproj_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 325)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.main_box = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.main_box.setContentsMargins(0, 0, 0, 0)
        self.main_box.setObjectName("main_box")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.main_box.addWidget(self.label)
        self.text_file = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.text_file.setObjectName("text_file")
        self.main_box.addWidget(self.text_file)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_file = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.name_file.setMinimumSize(QtCore.QSize(200, 25))
        self.name_file.setObjectName("name_file")
        self.horizontalLayout.addWidget(self.name_file)
        self.append_file = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.append_file.setMinimumSize(QtCore.QSize(120, 25))
        self.append_file.setMaximumSize(QtCore.QSize(120, 25))
        self.append_file.setObjectName("append_file")
        self.horizontalLayout.addWidget(self.append_file)
        self.append_dir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.append_dir.setMinimumSize(QtCore.QSize(120, 25))
        self.append_dir.setMaximumSize(QtCore.QSize(120, 25))
        self.append_dir.setObjectName("append_dir")
        self.horizontalLayout.addWidget(self.append_dir)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.bt_del = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_del.setMinimumSize(QtCore.QSize(120, 25))
        self.bt_del.setMaximumSize(QtCore.QSize(120, 25))
        self.bt_del.setObjectName("del")
        self.horizontalLayout.addWidget(self.bt_del)
        self.open = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open.setMinimumSize(QtCore.QSize(120, 25))
        self.open.setMaximumSize(QtCore.QSize(120, 25))
        self.open.setObjectName("open")
        self.horizontalLayout.addWidget(self.open)
        
        self.open_dir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_dir.setMinimumSize(QtCore.QSize(120, 25))
        self.open_dir.setMaximumSize(QtCore.QSize(120, 25))
        self.open_dir.setObjectName("open")
        self.horizontalLayout.addWidget(self.open_dir)
        self.main_box.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Комментарий к файлу"))
        self.append_file.setText(_translate("Form", "Добавить файл"))
        self.append_dir.setText(_translate("Form", "Добавить папку"))
        self.bt_del.setText(_translate("Form", "Удалить из проекта"))
        self.open.setText(_translate("Form", "Открыть"))
        self.open_dir.setText(_translate("Form", "Открыть папку"))



